name: 'SECURITY-INSIGHTS Validator'
author: 'Luigi Gubello'
description: 'Run SECURITY-INSIGHTS validator (ossf/si-tooling) as GitHub Action workflow.'
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  security_insights_path:
    description: 'Local path of SECURITY-INSIGHTS.yml.'
    required: true
    default: './SECURITY-INSIGHTS.yml'
  schema_version:
    descrition: 'Version of the SECURITY-INSIGHTS schema (vX.Y.Z) or the local path.'
    required: true
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'